In [1]:
import numpy as np

In [2]:
np.__version__

'2.0.1'

## Create and Read

### 1D Array

In [3]:
arr1 = np.array([1,2,3,4,5])
arr1

array([1, 2, 3, 4, 5])

In [4]:
type(arr1)

numpy.ndarray

In [5]:
arr1.shape

(5,)

In [6]:
arr1.dtype

dtype('int64')

In [7]:
arr1.ndim

1

In [8]:
arr1.size

5

### 2D Array

In [10]:
arr2 = np.array([[1,4,6], [6,7,4]])
arr2

array([[1, 4, 6],
       [6, 7, 4]])

In [11]:
arr2.ndim

2

In [12]:
arr2.shape #(row, column)

(2, 3)

In [13]:
arr2.size

6

### 3D Array

In [18]:
arr3 = np.array([[[1,4,6], [6,7,4]], [[3,5,4], [5,8,7]], [[1,4,6], [6,7,4]]])
arr3

array([[[1, 4, 6],
        [6, 7, 4]],

       [[3, 5, 4],
        [5, 8, 7]],

       [[1, 4, 6],
        [6, 7, 4]]])

In [19]:
arr3.ndim

3

In [20]:
arr3.shape

(3, 2, 3)

In [21]:
arr3.size

18

### Create random array

In [22]:
randomArr = np.random.rand(3,2,3)
randomArr

array([[[0.05776126, 0.77525697, 0.61181907],
        [0.73621043, 0.71357169, 0.98469092]],

       [[0.54965966, 0.92733992, 0.97122059],
        [0.67358432, 0.65807066, 0.78171147]],

       [[0.07156887, 0.97890585, 0.49305343],
        [0.52462111, 0.13156342, 0.99369895]]])

In [23]:
randomArr.dtype

dtype('float64')

In [24]:
zeros = np.zeros((3,2,3))
zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [25]:
zeros.ndim

3

In [26]:
full = np.full((3,2,3), 8)
full

array([[[8, 8, 8],
        [8, 8, 8]],

       [[8, 8, 8],
        [8, 8, 8]],

       [[8, 8, 8],
        [8, 8, 8]]])

In [28]:
ones = np.ones((3,2,3))
ones

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [29]:
arr3

array([[[1, 4, 6],
        [6, 7, 4]],

       [[3, 5, 4],
        [5, 8, 7]],

       [[1, 4, 6],
        [6, 7, 4]]])

In [34]:
arr3[0][0][2]

np.int64(6)

In [35]:
arr3[0:2]

array([[[1, 4, 6],
        [6, 7, 4]],

       [[3, 5, 4],
        [5, 8, 7]]])

In [36]:
arr3[0:3]

array([[[1, 4, 6],
        [6, 7, 4]],

       [[3, 5, 4],
        [5, 8, 7]],

       [[1, 4, 6],
        [6, 7, 4]]])

In [38]:
arr3[-1] ## last index

array([[1, 4, 6],
       [6, 7, 4]])

In [39]:
arr3[1,0,1]

np.int64(5)

In [41]:
a1 = np.random.rand(2,3,2)
a2 = np.random.rand(2,3,2)

In [42]:
a1

array([[[0.06581076, 0.60566365],
        [0.24588942, 0.18287102],
        [0.5029788 , 0.70047554]],

       [[0.74250177, 0.47539263],
        [0.63118429, 0.81825794],
        [0.34045768, 0.97220152]]])

In [43]:
a2

array([[[0.83188782, 0.24866604],
        [0.04013918, 0.95590914],
        [0.91751644, 0.04143226]],

       [[0.30211063, 0.11960195],
        [0.04535171, 0.20054507],
        [0.86525534, 0.8902025 ]]])

#### Basic Math Operations

In [44]:
np.add(a1,a2)

array([[[0.89769858, 0.85432968],
        [0.2860286 , 1.13878016],
        [1.42049523, 0.7419078 ]],

       [[1.0446124 , 0.59499458],
        [0.67653601, 1.01880301],
        [1.20571302, 1.86240402]]])

In [45]:
np.subtract(a1, a2)

array([[[-0.76607706,  0.35699761],
        [ 0.20575023, -0.77303813],
        [-0.41453764,  0.65904328]],

       [[ 0.44039114,  0.35579068],
        [ 0.58583258,  0.61771287],
        [-0.52479766,  0.08199902]]])

In [46]:
np.multiply(a1, a2)

array([[[0.05474717, 0.15060798],
        [0.0098698 , 0.17480808],
        [0.46149131, 0.02902228]],

       [[0.22431768, 0.05685789],
        [0.02862529, 0.16409759],
        [0.29458283, 0.86545622]]])

In [47]:
np.divide(a1,a2)

array([[[ 0.07911014,  2.43565084],
        [ 6.12591949,  0.19130585],
        [ 0.54819595, 16.90652576]],

       [[ 2.45771479,  3.97479002],
        [13.91754084,  4.08016986],
        [ 0.39347655,  1.09211277]]])

### Statistical operations

In [49]:
sqrt = np.sqrt(25)
abs = np.abs(-2)
power = np.power(2, 8)
log = np.log(2)
mins = np.min(a1)
maxs = np.max(a2)

In [50]:
sqrt

np.float64(5.0)

In [51]:
abs

np.int64(2)

In [52]:
power

np.int32(256)

In [53]:
log

np.float64(0.6931471805599453)

In [54]:
mins

np.float64(0.06581075873237008)

In [55]:
maxs

np.float64(0.9559091440409687)

### Update

In [56]:
arr3

array([[[1, 4, 6],
        [6, 7, 4]],

       [[3, 5, 4],
        [5, 8, 7]],

       [[1, 4, 6],
        [6, 7, 4]]])

In [57]:
arr3[0,0,2] = 500
arr3

array([[[  1,   4, 500],
        [  6,   7,   4]],

       [[  3,   5,   4],
        [  5,   8,   7]],

       [[  1,   4,   6],
        [  6,   7,   4]]])

In [58]:
arr3.sort()
arr3

array([[[  1,   4, 500],
        [  4,   6,   7]],

       [[  3,   4,   5],
        [  5,   7,   8]],

       [[  1,   4,   6],
        [  4,   6,   7]]])

In [59]:
# Reshape
arr3.shape

(3, 2, 3)

In [60]:
arr3_reshape = arr3.reshape((2,3,3))
arr3_reshape

array([[[  1,   4, 500],
        [  4,   6,   7],
        [  3,   4,   5]],

       [[  5,   7,   8],
        [  1,   4,   6],
        [  4,   6,   7]]])

In [61]:
arr3_reshape.shape

(2, 3, 3)

### Appending and Inserting

In [62]:
zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [63]:
# Create a new array
new_array = np.ones((3,2,3))
new_array

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [65]:
appd = np.append(zeros, new_array, axis=0)
appd

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [66]:
# Insert

In [67]:
zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [68]:
new_array

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [69]:
inserted_array = np.insert(zeros, 1, new_array, axis=0)
inserted_array

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

### Delete

In [70]:
arr4 = np.random.rand(3,2,3)
arr4

array([[[0.9595303 , 0.4895827 , 0.43929301],
        [0.88812294, 0.4341462 , 0.42549576]],

       [[0.53872001, 0.66839333, 0.81257779],
        [0.52084491, 0.58007819, 0.7399483 ]],

       [[0.22557334, 0.32448021, 0.73108263],
        [0.04483129, 0.85742153, 0.36135741]]])

In [72]:
# delete the array
arr5 = np.delete(arr4, 0, axis=1)

In [73]:
arr5

array([[[0.88812294, 0.4341462 , 0.42549576]],

       [[0.52084491, 0.58007819, 0.7399483 ]],

       [[0.04483129, 0.85742153, 0.36135741]]])

In [74]:
np.save("new_array", arr5)

In [75]:
np.load("new_array.npy")

array([[[0.88812294, 0.4341462 , 0.42549576]],

       [[0.52084491, 0.58007819, 0.7399483 ]],

       [[0.04483129, 0.85742153, 0.36135741]]])